global:
  scrape_interval: 60s

remote_write:
  - url: https://prometheus-prod-66-prod-us-east-3.grafana.net/api/prom/push
    basic_auth:
      username: 3030640
      password: ${GRAFANA_CLOUD_TOKEN}

scrape_configs:
  - job_name: rl-platform
    static_configs:
      - targets: ["api:8000"]
    metrics_path: /metrics